meta:
  version: 2
  flow: Classic
  substituting_steps:
    # Add steps for LVS with KLayout
    +Checker.LVS: OpenROAD.WriteCDL
    +OpenROAD.WriteCDL: KLayout.LVS
DESIGN_NAME: controller
FP_PDN_MULTILAYER: false
VERILOG_FILES:
  - dir::rtl/controller/controller.v
  - dir::rtl/controller/config_usb_cdc.v
  - dir::rtl/controller/jtag_bridge.v
  - dir::rtl/controller/usb_cdc/bulk_endp.v
  - dir::rtl/controller/usb_cdc/ctrl_endp.v
  - dir::rtl/controller/usb_cdc/usb_cdc.v
  - dir::rtl/controller/usb_common/in_fifo.v
  - dir::rtl/controller/usb_common/out_fifo.v
  - dir::rtl/controller/usb_common/phy_tx.v
  - dir::rtl/controller/usb_common/phy_rx.v
  - dir::rtl/controller/usb_common/sie.v
CLOCK_PERIOD: 21.833
CLOCK_PORT:
  - clk_system_i
  - clk_usb_i
DIE_AREA: [0, 0, 300, 300]
BOTTOM_MARGIN_MULT: 1
TOP_MARGIN_MULT: 1
LEFT_MARGIN_MULT: 6
RIGHT_MARGIN_MULT: 6
RT_MAX_LAYER: TopMetal1
FP_PDN_HORIZONTAL_LAYER: TopMetal2
FP_PDN_VPITCH: 50
SYNTH_ELABORATE_FLATTEN: false
SYNTH_NO_FLAT: 1
DRT_THREADS: 8
DESIGN_REPAIR_MAX_CAP_PCT: 30
GRT_ALLOW_CONGESTION: true
MAX_FANOUT_CONSTRAINT: 5
FP_CORE_UTIL: 91
PL_TARGET_DENSITY_PCT: 95
FP_PPL_MODE: random_equidistant
PL_RESIZER_HOLD_MAX_BUFFER_PCT: 50
GRT_RESIZER_HOLD_SLACK_MARGIN: 1.0
PL_RESIZER_SETUP_SLACK_MARGIN: 4
PL_RESIZER_ALLOW_SETUP_VIOS: true
# RUN_HEURISTIC_DIODE_INSERTION: true
RUN_ANTENNA_REPAIR: true
FALLBACK_SDC: dir::clocks.sdc
SYNTH_STRATEGY: AREA 2
VERILOG_DEFINES: [USB_CDC]
FP_SIZING: absolute
LINTER_DEFINES:
  - Wno-TIMESCALEMOD
